-- Local/dev seeds are loaded via [db.seed].sql_paths in supabase/config.toml.
-- Supabase CLI does not support psql meta-commands (\i, \echo, etc.) during db reset.
-- See supabase/seeds/dev_raw_materials.sql and supabase/seeds/order_menu_catalog.sql.
