export const ORDER_COPY = {
  registryTitle: "Registrar pedido",
  kitchenTitle: "Cola de cocina",
  serviceTakeOut: "Para llevar",
  serviceDelivery: "Delivery",
  fulfillmentTitle: "Entrega",
  fulfillmentImmediate: "Entrega inmediata",
  fulfillmentScheduled: "Orden posterior",
  fulfillmentImmediateBadge: "Inmediato",
  readyByDateLabel: "Fecha",
  readyByTimeLabel: "Hora",
  readyByTimezoneHint: (timezone: string) =>
    `Hora local del local (${timezone}). Mínimo 5 minutos; máximo 7 días.`,
  customerSectionTitle: "Cliente (opcional)",
  customerFirstName: "Nombre",
  customerLastName: "Apellido",
  customerPhone: "Teléfono",
  deliveryZoneLabel: "Zona (opcional)",
  deliveryFeeLabel: "Costo de envío",
  deliveryFeeRequired: "Ingresa el costo de envío",
  itemsSubtotal: "Subtotal artículos",
  deliveryFeeLine: "Costo de envío",
  total: "Total",
  sendToKitchen: "Enviar a cocina",
  markReady: "Marcar listo",
  emptyKitchen: "No hay pedidos en cocina.",
  reconnecting: "Reconectando…",
  submitSuccess: "Pedido enviado a cocina.",
  submitError: "No se pudo enviar el pedido.",
  markReadyError: "Pedido no disponible.",
  meatSidesTitle: "Selecciona contornos",
  sideSlot1: "Contorno 1",
  sideSlot2: "Contorno 2",
  confirmAdd: "Agregar al carrito",
  cancel: "Cancelar",
  drinks: "Bebidas",
  beef: "Res",
  pork: "Cerdo",
  chicken: "Pollo",
} as const;

export const KITCHEN_SLA_MINUTES = 20;
