export const ORDER_COPY = {
  registryTitle: "Registrar pedido",
  kitchenTitle: "Cola de cocina",
  serviceTakeOut: "Para llevar",
  serviceDelivery: "Delivery",
  deliveryZoneLabel: "Zona (opcional)",
  deliveryFeeLabel: "Costo de envío",
  deliveryFeeRequired: "Ingresa el costo de envío",
  itemsSubtotal: "Subtotal artículos",
  deliveryFeeLine: "Costo de envío",
  total: "Total",
  sendToKitchen: "Enviar a cocina",
  markReady: "Marcar listo",
  emptyKitchen: "No hay pedidos en cocina.",
  reconnecting: "Reconectando…",
  submitSuccess: "Pedido enviado a cocina.",
  submitError: "No se pudo enviar el pedido.",
  markReadyError: "Pedido no disponible.",
  meatSidesTitle: "Selecciona contornos",
  sideSlot1: "Contorno 1",
  sideSlot2: "Contorno 2",
  confirmAdd: "Agregar al carrito",
  cancel: "Cancelar",
  drinks: "Bebidas",
  beef: "Res",
  pork: "Cerdo",
  chicken: "Pollo",
} as const;

export const KITCHEN_SLA_MINUTES = 20;
